cf_clearance: HBR_Hyp5ExKhd4tncXiCfFf_MiUyCUrIlZi_k.A92t8-1741958790-1.2.1.1-LLX2aFXyF5bgewUCazpl0EcwZOANrG3yQTQTnPQujm4N_LBQ6gOZch9eoWm8TLW..og8bB3OkvMSA_v6089KrlK7YLnfCsjeb75n1Hbp3rLuGJf6wjlz3a4VQFw7ljVlL3Sg6ZN1J1TzTAG5JpDEIOaLN9zz.MNP6eCPi2Qz0lbE3dh37Os_1ycNNQHjT_K_ZZbzqsbW4Yd5T6UsRfvrUB_fkHqaCNa4R7_cOLOMwRK643cPAu_dM4kFIVKnI2mDZJDGxX8OOEzPQvsC0RzWtbjZn2Xhs0BTwHBbo7C.z8ijouzHwKsCZe6PUtELiSdECHjH_4nB8X36htjgr0DdqmvVM.A_RBQgsI2BmdoSokk
coords:
  - 2:308:4
expedition_count: 12
fleet_speed: 8
fs:
  - 4:314:4
game_auth_token: xd.eyJpYXQiOjE3NDE5NTg3OTcsImV4cCI6MjA1NzQ5MTU5NywiSWQiOiJhOTU5ZjRjNC1iN2Q0LTQ2MjMtODM3Ny1lODk4ZmM5ZDMwM2EiLCJTZXNzaW9uSWQiOiJjMDQ5OWFjMS1lNmE2LTQ5NWUtYWU2My0wMzk0ZDZjNzcwNjAifQ.-_WFT37i9Owspxm59uSgf0ezy9aReSPk2iSyVoz-j3U
host: https://falcon.ogamex.net
login: xd
miners_percentage_start: 80
miners_speed: 112000
password: xd
session_id: xd
