host: "https://hyper.ogamex.net"
fleet_speed: 6
login: "tijaci2136@sectorid.com"
password: "BazAstral123"
session_id: "vemh5pgpm3wbn3nbrbybqjn0"
game_auth_token: "eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzkwNDUyMDMsImV4cCI6MjA1NDU3ODAwMywiSWQiOiIzYTBjYmE1Ny1iYTU3LTQyZGItYjVjMS1iMzUyOTFkMDA0N2QiLCJTZXNzaW9uSWQiOiI5OGE0OGQxMC1jZWUxLTRlNjgtYTkxMC01NWM4N2E5YTM2NGUifQ.kBTda8Qkbu1KeSxhQLK55mBcVkQFAZa1M2_F8bGfUp0"
cf_clearance: "79LMaMHaeWo0rMjOKOBXLOQyDZPNx3BbdN8GmqZJYcw-1739048692-1.2.1.1-WzFyZc2IMbPdro15IxM3doXPpxw66q7pV_MPEBvEaDkg.0T5KoEOz5LvLWhT5KorU296fSK2J2H9QImhgDz7RqJQdrOBYeTA.ZRSHBM5v13lZwKvDi5bgRWT7KAPvLg4wbsEIh1ESq8GaBe8JmaMYLXfzYwpgsE9xDKTHMGN45p6a5VFT0CMEkIoaamay_yIFNvOAHGfTDLsHJKWNYeAy1Zm5KXFQo7JE65xuQhzbpxzEcrzeBipXZ.tUT0oYDDNkAdEZKHd6InkjveIzRs6_sRLp80HKtGMxDdIBN0dbts"
coords: ["4:314:11"]
