cf_clearance: 1AxW_9z9DvED8ggh78h3D.PsUu0P4EkRgj504hY4Uf8-1742853380-1.2.1.1-Q6UBvIylGk4ZtpNo1fZjrOuv9O_jH5h0VC9NDDvySAvJTe9bUXJ8F8tAlvSb_KBt3dDHp9e4TVxTLgZPDunZwpE2v728fDUCKPTVw2HHvI6lTgCoNcWhQnbFuimFWUgGiTzyE6OUGbTT8hS.6a..TtCO3I486ixYE9F0I.nfmxWwqJcXsEP4eu3IATThF7di3PrJXNKykVD.f9iIDFGGG3YiOGmGjI.HnQdPj7nbAlRiZvX5DXZZHaQMlCfz_UyvajmPaWujK3Bq6JbPjKhYfxxiV1kVySG4C.Y4RBnCoa2g4vyWOcA.DcqVqRxsyl4C1WJ_RoiBjAhHukqiaPZA2Yael3evjUwV5qIsVUtIUps
coords:
- 2:308:4
expedition_count: 12
fleet_speed: 8
fs:
- 2:299:6
game_auth_token: eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDI4NTMzODYsImV4cCI6MjA1ODM4NjE4NiwiSWQiOiJhOTU5ZjRjNC1iN2Q0LTQ2MjMtODM3Ny1lODk4ZmM5ZDMwM2EiLCJTZXNzaW9uSWQiOiIxNGJkYjBmMS0yZTc2LTRlYjgtYmM2NS04YWM2NjVmZmUyNDIifQ.WTbdjhAPToqXy8OjZvhOScFeURH_NaAV1lUTjqTnCIw
host: https://falcon.ogamex.net
login: wurbanczyksii@gmail.com
miners_percentage_start: 100
miners_speed: 112000
password: RMDJ@EJe7jy52xg
session_id: lgfv3lv1ynqw0hope4fa1t0h
