cf_clearance: 7Y_cly6MlCI.kGSV68wdCXBBXdROKKCkL2rVtbqNQHA-1741199975-1.2.1.1-g1Oaukhbq6UBwseDQ0LCU0aFfmyJPPTuQeDcbfSrCkGPAKfg8016uAbZCV31IUd0K3h8DjJuZV4DTmts1hamm1vUKByoaGDeNeG0OYeigNFRVOJChmH3bx2_r0x2_AYzhSB3mskmT1JN9r2dyFntdGCF3u.dLpqD5QZOMynW4gIt2AXQ3kZqzGwInpz4wSkY.nBeB2emGXAa6jfqaX.VCgUwL29XykzpGAfVwN6mtDAInUbCPAlot.z.GzQk7LcNtZJMCwhLrQRYOfWUAGzgpJEQ9bBMWMHQrW9broXN0YGXf5Ii4woeTo1U7KpSW00c_78EENvLAmhnpC8N7svP2enVImlMT9RPcdjHG._L2AJDpCI43asq7hVB_jiBOVWRG1RQdGs7nXZ2hwDr9mZDYmApbZTPbXtXNCOVplY_sdc
coords:
  - 4:314:11
  - 4:314:13
fleet_speed: 6
fs:
  - 4:314:4
  - 4:314:4
game_auth_token: eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDExOTk5ODEsImV4cCI6MjA1NjczMjc4MSwiSWQiOiJhYWNlNzVhZC02ZmExLTRmMmUtYTI1Ni02ZjAxMThmNDVmZjQiLCJTZXNzaW9uSWQiOiIzM2E0MTViZC03YjZjLTQ3M2EtYTQ0Ni1iMThiZWVjNWM2YWUifQ.zE-Qk0LZPTMB3Q-rbdeSE4RNL4ji6GL6QEA0TzNwhi0
host: https://hyper.ogamex.net
login: tijaci2136@sectorid.com
miners_speed: 97680
password: BazAstral123
session_id: draxsvg245t5hcgpjartfirh
